---
title: "ASSINGMENT 3 ( Q1 )"
author: "Anmol Verma (45679215)"
date: "10/3/2019"
output: html_document
---
```{r}
j = 0.0192308
```

```{r}
qx = c(0.001046, 0.001199, 0.001375)
benefit_at_the_end = 15000*(1+j)^(0:2)
initailexpense = c(100+0.015*40250, 0, 0)
premium = c(1,0,0)*40250
```

```{r}
annuity_paymentexpense = 10*1.05^(0:2)
```
```{r}
policyvalue_end = c(c(1-0.889132, (1 - 0.924607)*(1+j))*15000/(0.04/1.04), 
                     15000*(1+j)^2) - 15000*(1+j)^(0:2)
```

```{r}
int_end = numeric()
int_end[1] = (premium[1] - initailexpense[1])*0.08
for(i in 2:3){int_end[i] = (policyvalue_end[i-1] - annuity_paymentexpense[i-1])*0.08}
```

```{r}
l = numeric(); l[1] = 100000
d = numeric()
for(i in 1:3){l[i+1] = l[i]*(1-qx[i]); d[i] = l[i]*qx[i]}
```

```{r}
p = premium*l[1:3]/l[1]; i_exp = initailexpense*l[1:3]/l[1]; int = int_end*l[1:3]/l[1]
a_exp = annuity_paymentexpense*l[2:4]/l[1]
policy_value = policyvalue_end*l[2:4]/l[1]
benefit = benefit_at_the_end*l[2:4]/l[1]
```

```{r}
transfer = p-i_exp+int-a_exp-benefit-diff(c(0,policy_value))

table1 = cbind(l, c(d,NA)); colnames(table1) = c("lx", "dx"); rownames(table1) = c(55:58)
table1
```
```{r}
inforce = cbind(premium, initailexpense, annuity_paymentexpense, int_end, benefit_at_the_end, policyvalue_end)
inforce
expected = cbind(p, initailexpense, a_exp, int, benefit, policy_value, transfer)
expected
```

Quesstion 1 (a)
The expected present value of transfer at the risk discount rate 12% is
transfer
```{r}
NPV = sum(transfer/(1.12)^(1:3))
margin = NPV / sum(premium/(1.12)^(0:2))
NPV;margin
```

Question 1(b)
```{r}
IRR = function(r){sum(transfer/(1+r)^(1:3))}
uniroot(IRR, c(0,1))[1]
```
IRR=50.328%
The IRR is very high because there is a big negative transfer (loss) in year 1, whereas the transfers are positive afterwards. Therefore, we need a large IRR to discount the latter year's cash flows to make Expected present value = 0.

